/**
 * Gen53 arm E-v2: arm C plus `quiescent-completion-toolcall-v2`.
 *
 * GENERATED from `pi_pilot_harness_state.ts` by
 * `scripts/build_pi_pilot_gen53_quiescent_v2.py`. Do not edit this file;
 * edit the generator or arm C.
 */
/**
 * Gen46 arm C: harness-maintained state and control, for the Gen47 live ablation.
 *
 * The composer, the caps and the history treatment are byte-for-byte arm B's.
 * The only difference is where the state and the phase come from: they are
 * derived here from ordinary visible tool events instead of waiting for the
 * model to call three tools it did not call in Gen45.
 *
 * The rules mirror `harness_state.py` exactly, and the preflight replays the
 * same synthetic event log through both to prove they agree. No semantic
 * interpretation, and nothing hidden — the final verifier and the reference
 * fixes are outside this path by construction.
 */
import { createHash } from "node:crypto";
import { appendFileSync, mkdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";

export const DERIVATION_VERSION = "harness-state-v1";

export const READ_TOOLS = new Set(["read", "ls", "grep", "find", "glob"]);
export const MUTATION_TOOLS = new Set(["edit", "write", "multi_edit"]);
export const VALIDATION_PATTERNS = [
  /\bpytest\b/,
  /\bpython3?\s+-m\s+pytest\b/,
  /\bpython3?\s+-m\s+unittest\b/,
  /\bpython3?\s+run_checks\.py\b/,
];
export const FORBIDDEN_IN_VALIDATION = ["verifier.py", "verifier_path", "reference_fix"];
export const INSPECTION_CALLS_TO_LEAVE_INSPECT = 2;

export const AUTOMATIC_TRANSITIONS: Record<string, string[]> = {
  inspect: ["plan", "implement", "blocked"],
  plan: ["implement", "inspect", "blocked"],
  implement: ["validate", "plan", "blocked"],
  validate: ["done", "implement", "blocked"],
  done: ["implement"],
  blocked: ["inspect", "plan", "implement", "validate"],
};

const STATE_BYTE_CAP = 4096;
const RECENT_FILES_BOUND = 6;
const CHECKPOINT_BOUND = 6;
const RECENT_WINDOW_UNITS = 2;
const RECENT_WINDOW_BYTE_CAP = 8192;
const LATEST_OBSERVATION_BYTE_CAP = 8192;

const IMMUTABLE_INSTRUCTIONS =
  "You are working under an executable control layer. Phases are inspect, plan, " +
  "implement, validate, done. The phase and the recorded state below are maintained " +
  "for you from what you do: reading moves you on from inspect, changing a file moves " +
  "you to implement, and running the project's own checks moves you to validate. " +
  "Completion is recorded only when a passing check matches the current tree.";

const canonical = (v: unknown) => JSON.stringify(v ?? null);
const sha256 = (t: string) => createHash("sha256").update(t).digest("hex");

export function isValidationCommand(command: string): boolean {
  if (!command) return false;
  if (FORBIDDEN_IN_VALIDATION.some((token) => command.includes(token))) return false;
  return VALIDATION_PATTERNS.some((pattern) => pattern.test(command));
}

const bounded = (values: string[], bound: number) => values.slice(Math.max(0, values.length - bound));

export interface DerivedState {
  schema_version: number;
  derivation: string;
  phase: string;
  revision: number;
  tree_digest: string;
  files_read: string[];
  files_modified: string[];
  last_tool: string;
  last_tool_ref: string;
  last_observation_ref: string;
  checkpoints: string[];
  validation: Record<string, unknown>;
  validated_artifact_refs: Array<Record<string, unknown>>;
}

export function newState(): DerivedState {
  return {
    schema_version: 1, derivation: DERIVATION_VERSION, phase: "inspect", revision: 0,
    tree_digest: "", files_read: [], files_modified: [], last_tool: "", last_tool_ref: "",
    last_observation_ref: "", checkpoints: [], validation: {}, validated_artifact_refs: [],
  };
}

export class Derivation {
  state = newState();
  transitions: Array<Record<string, unknown>> = [];
  receipts: Array<Record<string, unknown>> = [];
  invalidations: Array<Record<string, unknown>> = [];
  inspectionCalls = 0;

  private move(target: string, because: string, ref: string) {
    const current = this.state.phase;
    if (target === current) return;
    if (!(AUTOMATIC_TRANSITIONS[current] ?? []).includes(target)) {
      this.transitions.push({ from: current, to: target, accepted: false,
        reason: "not an automatic transition", event: ref });
      return;
    }
    this.state.phase = target;
    this.state.revision += 1;
    this.transitions.push({ from: current, to: target, accepted: true, because, event: ref });
  }

  private checkpoint(name: string) {
    this.state.checkpoints = bounded([...this.state.checkpoints, name], CHECKPOINT_BOUND);
  }

  private invalidateOnMutation(ref: string) {
    if (this.state.validated_artifact_refs.length === 0) return;
    this.invalidations.push({ reason: "repository mutated after the check",
      receipt: this.state.validated_artifact_refs[0], event: ref });
    this.state.validated_artifact_refs = [];
  }

  toolCall(tool: string, args: any, ref: string) {
    this.state.last_tool = tool;
    this.state.last_tool_ref = ref;
    this.state.revision += 1;
    if (READ_TOOLS.has(tool)) {
      this.inspectionCalls += 1;
      const path = args?.path ?? args?.pattern ?? "";
      if (path) {
        this.state.files_read = bounded(
          [...this.state.files_read.filter((p) => p !== path), path], RECENT_FILES_BOUND);
      }
      if (this.state.phase === "inspect" && this.inspectionCalls >= INSPECTION_CALLS_TO_LEAVE_INSPECT) {
        this.move("plan", "enough inspection activity to have looked around", ref);
      }
    } else if (MUTATION_TOOLS.has(tool)) {
      const path = args?.path ?? "";
      if (path) {
        this.state.files_modified = bounded(
          [...this.state.files_modified.filter((p) => p !== path), path], RECENT_FILES_BOUND);
      }
      this.checkpoint("repository_mutated");
      this.invalidateOnMutation(ref);
      if (["inspect", "plan", "validate", "done"].includes(this.state.phase)) {
        this.move("implement", "the repository was modified", ref);
      }
    }
  }

  toolResult(command: string, exitCode: number | undefined, isError: boolean, tree: string, ref: string) {
    this.state.last_observation_ref = ref;
    if (tree) this.state.tree_digest = tree;
    const trimmed = (command ?? "").trim();
    if (!trimmed || !isValidationCommand(trimmed)) return;
    const passed = exitCode === undefined ? !isError : exitCode === 0;
    this.state.validation = { command: trimmed, passed, tree_digest: this.state.tree_digest, event: ref };
    if (this.state.phase === "implement") this.move("validate", "a visible check ran after a change", ref);
    if (passed) {
      this.checkpoint("validation_passed");
      const receipt = { kind: "validation_receipt", command: trimmed,
        tree_digest: this.state.tree_digest, passed: true, event: ref };
      this.state.validated_artifact_refs = [receipt];
      this.receipts.push(receipt);
    } else {
      this.checkpoint("validation_failed");
      this.state.validated_artifact_refs = [];
      if (this.state.phase === "validate") this.move("implement", "the visible check failed", ref);
    }
  }

  sessionEnd(ref: string) {
    if (this.validReceipt() && this.state.phase === "validate") {
      this.move("done", "the run ended with a valid receipt for this tree", ref);
    }
  }

  validReceipt(): Record<string, unknown> | null {
    for (const receipt of this.state.validated_artifact_refs) {
      if (receipt.passed && receipt.tree_digest === this.state.tree_digest) return receipt;
    }
    return null;
  }

  summary() {
    return {
      state: this.state,
      state_bytes: canonical(this.state).length,
      transitions: this.transitions,
      transitions_accepted: this.transitions.filter((t) => t.accepted).length,
      transitions_rejected: this.transitions.filter((t) => !t.accepted).length,
      receipts: this.receipts,
      receipt_invalidations: this.invalidations,
      valid_receipt_at_end: this.validReceipt() !== null,
    };
  }
}

// --- the extension -----------------------------------------------------------

type Message = { role: string; content: unknown };

function interactionUnits(messages: Message[]): Message[][] {
  const units: Message[][] = [];
  let current: Message[] | null = null;
  for (const message of messages) {
    if (message.role === "user") { if (current) units.push(current); current = [message]; }
    else if (current) current.push(message);
  }
  if (current) units.push(current);
  return units;
}

function recentWindow(messages: Message[]): Message[] {
  const selected = interactionUnits(messages).slice(-RECENT_WINDOW_UNITS).flat();
  const kept: Message[] = [];
  let used = 0;
  for (let i = selected.length - 1; i >= 0; i--) {
    const size = canonical(selected[i]).length;
    if (used + size > RECENT_WINDOW_BYTE_CAP) break;
    kept.unshift(selected[i]);
    used += size;
  }
  return kept;
}


/* ---------------------------------------------------------------------------
 * `quiescent-completion-toolcall-v2`, the Gen52 repair.
 *
 * v1 stopped a run that had reverted its own correct fix, because it asked only
 * whether a mutation had happened and never whether the tree had changed. And
 * it never stopped a run that ran the same passing test 144 times, because each
 * pass re-armed the receipt and reset the count.
 *
 * So: a tree back at its starting digest is never complete, and a pass on a
 * tree that already holds a receipt is an idle action. Nothing else changes.
 *
 * The hidden verifier is outside this path by construction, and the recognizer
 * is arm C's own. A tool that is still running is never killed.
 * ------------------------------------------------------------------------ */
export const STOP_CONTRACT = "quiescent-completion-toolcall-v2";
export const STOP_K = 3;

export class QuiescentStopV2 {
  initialTree = "";
  currentTree = "";
  mutated = false;
  receiptTree: string | null = null;
  receiptIndex: number | null = null;
  idle = 0;
  toolIndex = 0;
  pendingCalls = 0;
  armed = false;
  triggered = false;
  triggerToolIndex: number | null = null;
  effectiveStopToolIndex: number | null = null;
  sameBatchOvershootCalls = 0;
  mutations = 0;
  sameTreePassesCountedIdle = 0;
  becameEligible = false;
  lastValidationEvent = "";
  lastVisibleCheckPassed: boolean | null = null;
  reason = "";

  netTreeChanged(): boolean {
    return Boolean(this.currentTree) && this.currentTree !== this.initialTree;
  }

  eligible(): boolean {
    return this.mutated && this.netTreeChanged()
      && this.receiptTree !== null && this.receiptTree === this.currentTree;
  }

  observeCall(tool: string): void {
    this.toolIndex += 1;
    this.pendingCalls += 1;
    if (MUTATION_TOOLS.has(tool)) {
      this.mutated = true;
      this.mutations += 1;
      this.invalidate();
    }
  }

  observeResult(validation: any, treeDigest: string): boolean {
    this.pendingCalls = Math.max(0, this.pendingCalls - 1);
    if (treeDigest) {
      if (!this.initialTree) this.initialTree = treeDigest;
      if (this.currentTree && treeDigest !== this.currentTree) {
        this.invalidate();      // the tree moved without a mutation tool
        this.mutated = true;
      }
      this.currentTree = treeDigest;
    }

    if (this.armed) {
      this.sameBatchOvershootCalls += 1;
      return this.pendingCalls === 0 && this.finish();
    }

    // `state.validation` is sticky, so only a new `event` ref means a check ran.
    const fresh = validation && validation.event && validation.event !== this.lastValidationEvent;
    if (fresh) this.lastValidationEvent = validation.event;
    const passed = fresh && typeof validation.passed === "boolean" ? validation.passed : null;
    if (passed !== null) this.lastVisibleCheckPassed = passed;

    if (passed === false) {
      this.invalidate();
      return false;
    }
    if (passed === true) {
      if (this.receiptTree !== null && this.receiptTree === this.currentTree) {
        this.sameTreePassesCountedIdle += 1;
        this.idle += 1;
      } else {
        this.receiptTree = this.currentTree;
        this.receiptIndex = this.toolIndex;
        this.idle = 0;
        if (this.eligible()) this.becameEligible = true;
        return false;
      }
    } else if (this.receiptTree !== null) {
      this.idle += 1;
    }

    if (!this.eligible()) return false;
    this.becameEligible = true;
    if (this.idle < STOP_K) return false;
    this.armed = true;
    this.triggerToolIndex = this.toolIndex;
    if (this.pendingCalls > 0) return false;
    return this.finish();
  }

  private invalidate(): void {
    this.receiptTree = null;
    this.receiptIndex = null;
    this.idle = 0;
  }

  private finish(): boolean {
    this.triggered = true;
    this.effectiveStopToolIndex = this.toolIndex;
    this.reason = "quiescent_stop";
    return true;
  }

  snapshot(): Record<string, unknown> {
    return {
      contract: STOP_CONTRACT, k: STOP_K,
      initial_tree_digest: this.initialTree,
      current_tree_digest: this.currentTree,
      net_tree_changed: this.netTreeChanged(),
      valid_receipt_tree: this.receiptTree,
      valid_receipt_tool_index: this.receiptIndex,
      idle_count: this.idle,
      eligible: this.eligible(),
      became_eligible: this.becameEligible,
      mutations: this.mutations,
      same_tree_passes_counted_idle: this.sameTreePassesCountedIdle,
      last_visible_check_passed: this.lastVisibleCheckPassed,
      triggered: this.triggered,
      trigger_tool_index: this.triggerToolIndex,
      effective_stop_tool_index: this.effectiveStopToolIndex,
      same_batch_overshoot_calls: this.sameBatchOvershootCalls,
      tool_index: this.toolIndex,
      reason: this.reason,
    };
  }
}

export default function quiescentV2Arm(pi: any) {
  const OUT = process.env.PI_PILOT_OUT ?? "/tmp/pi-pilot-run";
  const WORKTREE = process.env.PI_PILOT_WORKTREE ?? process.cwd();
  mkdirSync(OUT, { recursive: true });
  const line = (name: string, payload: unknown) =>
    appendFileSync(join(OUT, name), canonical(payload) + "\n");

  const derivation = new Derivation();
  const stop = new QuiescentStopV2();
  let latestObservation: unknown = null;
  let seq = 0;
  const nextRef = () => `e${String(seq++).padStart(6, "0")}`;

  /**
   * Tree digest of the working tree, computed WITHOUT touching the real index.
   *
   * The first version ran `git add -A` against the real index on every tool
   * result. That is observable: the agent can see staged files with an ordinary
   * `git status`, and only arm C would have caused it, so it would have been a
   * treatment difference rather than an observation. This builds the same tree
   * in a temporary alternate index seeded from HEAD and throws it away.
   */
  const treeDigest = () => {
    const indexFile = join(OUT, `.tree-index-${process.pid}`);
    const env = { ...process.env, GIT_INDEX_FILE: indexFile };
    try {
      execFileSync("git", ["read-tree", "HEAD"], { cwd: WORKTREE, env, stdio: "ignore" });
      execFileSync("git", ["add", "-A"], { cwd: WORKTREE, env, stdio: "ignore" });
      return execFileSync("git", ["write-tree"], { cwd: WORKTREE, env }).toString().trim();
    } catch {
      return "";
    } finally {
      try { rmSync(indexFile, { force: true }); } catch { /* nothing to remove */ }
    }
  };

  stop.initialTree = treeDigest();
  stop.currentTree = stop.initialTree;

  const persistStop = () => {
    const target = join(OUT, "quiescent_stop.json");
    const staging = join(OUT, `.quiescent_stop.json.${process.pid}`);
    writeFileSync(staging, canonical(stop.snapshot()));
    renameSync(staging, target);
  };

  const persist = () => writeFileSync(join(OUT, "harness_state.json"),
    canonical({ ...derivation.summary(), derivation_version: DERIVATION_VERSION }));

  pi.on("context", (event: any) => {
    const incoming: Message[] = event.messages ?? [];
    const observation = canonical(latestObservation).length > LATEST_OBSERVATION_BYTE_CAP
      ? { truncated: true, note: "full tool output retained in history" } : latestObservation;
    const stateView = canonical(derivation.state).length > STATE_BYTE_CAP
      ? { truncated: true, phase: derivation.state.phase } : derivation.state;
    const view = {
      instructions: IMMUTABLE_INSTRUCTIONS,
      control: { phase: derivation.state.phase,
                 legal_next: AUTOMATIC_TRANSITIONS[derivation.state.phase] ?? [],
                 maintained_by: "harness" },
      state: stateView,
      latest_observation: observation,
      artifact_refs: derivation.state.validated_artifact_refs,
    };
    const replacement = [
      { role: "user", content: [{ type: "text", text: canonical(view) }] },
      ...recentWindow(incoming),
    ];
    line("requests.ndjson", { bytes: canonical(replacement).length, messages: replacement.length,
      composed: true, pi_would_have_sent_bytes: canonical(incoming).length,
      state_bytes: canonical(derivation.state).length, phase: derivation.state.phase });
    return { messages: replacement };
  });


  // Observation only. Pi's runner keeps the original payload unless a handler
  // returns something (`if (handlerResult !== undefined)` in runner.js), so
  // returning nothing here cannot rewrite the request. This is the only place
  // the FULL provider payload is visible, including tool schemas, which matters
  // because the two arms offer different tool surfaces.
  pi.on("before_provider_request", (event: any, ctx: any) => {
    if (stop.armed) { persistStop(); ctx?.abort?.(); return; }
    line("payloads.ndjson", { bytes: JSON.stringify(event.payload ?? null).length });
  });

  pi.on("session_before_compact", () => ({ cancel: true }));

  pi.on("tool_call", (event: any, ctx: any) => {
    const ref = nextRef();
    const tool = event.toolName ?? event.type;
    derivation.toolCall(tool, event.input ?? {}, ref);
    stop.observeCall(tool);
    line("tools.ndjson", { phase: "call", tool, args: event.input ?? {} });
    line("derivation.ndjson", { ref, kind: "tool_call", tool, phase: derivation.state.phase });
    persist();
    return {};
  });

  pi.on("tool_result", (event: any, ctx: any) => {
    const ref = nextRef();
    const text = canonical(event.result ?? event.content ?? "");
    const command = event?.input?.command ?? event?.input?.cmd ?? "";
    const tool = event.toolName ?? "";
    const exit = event?.result?.exitCode ?? event?.details?.exitCode;
    derivation.toolResult(command, exit, Boolean(event.isError), treeDigest(), ref);
    latestObservation = { event_id: ref, bytes: text.length,
      text: text.slice(0, LATEST_OBSERVATION_BYTE_CAP) };
    line("tools.ndjson", { phase: "result", tool, bytes: text.length });
    line("derivation.ndjson", { ref, kind: "tool_result", command,
      phase: derivation.state.phase, validation: derivation.state.validation });
    persist();
    const stopNow = stop.observeResult(derivation.state.validation,
                                       derivation.state.tree_digest);
    persistStop();   // every result, not only at a stop
    if (stopNow) ctx?.abort?.();
    return {};
  });

  pi.on("session_shutdown", () => {
    derivation.sessionEnd(nextRef());
    persist();
    persistStop();
  });
}
