#!/usr/bin/env python3
"""Gate for QUEUE row D-7 (the board's own timestamps are not evidence).

plumb-fable, row D-7G, 2026-09-17. Written FROM ROW D-7's TEXT ALONE, before any
D-7 artifact existed (`team/D-7-timestamps/` was absent). This gate is an
INSTRUMENT, not a receipt: it does not trust report.md's account of the stamps,
it re-derives the comparison from the board and the filesystem on every run.

Extended corvid-dsh, row D-12 (2026-09-17): verify-receipt excusal. The four
S7-*G verify closes tripped this gate at 15:42 with true, clock-read stamps —
a reviewer closing a row later is ELAPSED TIME, not skew. Declared in the row
before implementation: a receipt `team/CORVID-<ROW>-VERIFY.md` whose mtime is
within tolerance BELOW the stamp excuses the lead; a receipt NEWER than the
stamp is its own finding; a stale receipt (older than tolerance below the
stamp) leaves the lead flagged. Authored by corvid, verified by kiln — the
gate is not refitted by the party it excuses.

Part 1 - the comparison, recomputed (marker in brackets)
  For every QUEUE.md row whose status carries a stamp
        done: [seat] YYYY-MM-DD HH:MM[:SS] [PDT|PST|UTC|Z|+hh:mm]
  AND whose declared artifact exists, take the artifact's newest mtime and:
    [FUTURE-STAMP]          the stamp is later than this check's own clock.
                            Never excused.
    [STAMP-LEADS-ARTIFACT]  the stamp is more than TOLERANCE (10 min, stated
                            in the output) ahead of the newest mtime. Work
                            cannot finish before its files do. Excused only
                            when the row carries a visible bracketed mark,
                            e.g. `[stamp unreliable: ...]`, or when a verify
                            receipt `team/CORVID-<ROW>-VERIFY.md` exists with
                            its mtime within TOLERANCE BELOW the stamp.
    [RECEIPT-AFTER-STAMP]   a verify receipt exists but is NEWER than the
                            stamp: a receipt written after the claimed close
                            is itself a stamp problem. Not excused.
    [SILENT-REWRITE]        a stamp differs from BASELINE - the board as it
                            stood when this gate was written, before D-7
                            touched anything - and the row does not carry
                            `[corrected - stamp: first written HH:MM ...]`
                            quoting the ORIGINAL time. History may be
                            corrected; it may not be corrected invisibly.
Part 2 - the report
    [MISSING-FILE]             report.md, fix.diff
    [DIFF-EMPTY]               fix.diff changes nothing
    [MECHANISM-UNNAMED]        report.md needs a line `Mechanism changed: ...`
                               naming a file that fix.diff REALLY changes
    [CAUSE-UNSTATED]           report.md needs a line `Cause: ...` (row part a)
    [CAUSE-IS-TIMEZONE]        the row rules a timezone out: the error is not
                               constant
    [STAMP-DECISION-UNSTATED]  report.md needs exactly one line
                               `Existing stamps: corrected` or
                               `Existing stamps: marked-unreliable`
    [DECISION-CONTRADICTS-BOARD]  says marked-unreliable, but stamps changed

Limit, stated on purpose: mtime is the newest write, so a later edit to an
artifact hides an earlier lead; and BASELINE only knows the stamps that existed
on 2026-09-17. Whether the stated cause is the TRUE cause stays with the named
verifier.

Exit contract (team/tools/check_checker_exit_contracts.py): 0 clean, 1 with a
named marker and the line `D-7 gate findings: N`, never a traceback.

Usage:
  python3 check.py [ROOT] [--queue QUEUE.md] [--tolerance-min N] [--now ISO]
  python3 check.py --selftest  # a future stamp REJECTED, a clean board ACCEPTED
"""
from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
FILES = ("report.md", "fix.diff")
TOLERANCE_MIN = 10
CLOCK_SLACK = timedelta(seconds=60)
TZ = {"PDT": -7, "PST": -8, "UTC": 0, "Z": 0}
STAMP = re.compile(
    r"\bdone(?:[-_]at)?:\s*(?:[A-Za-z][\w.-]*\s+)?"
    r"(\d{4}-\d{2}-\d{2})[ T](\d{2}:\d{2}(?::\d{2})?)\s*(PDT|PST|UTC|Z|[+-]\d{2}:?\d{2})?")
BRACKET = re.compile(r"\[([^\]]*)\]")
PLACEHOLDER = re.compile(r"^(?:|tbd|todo|pending|n/?a|none|unknown|\?+|-+)$", re.I)

# The board's done-stamps as they stood when this gate was written (2026-09-17,
# before D-7 was claimed). Generated by _stamps() below, not typed.
BASELINE: dict[str, str] = {
    "S4-1": "2026-09-16T10:01:00-07:00",
    "S4-2": "2026-09-16T10:06:00-07:00",
    "S4-5": "2026-09-16T12:35:00-07:00",
    "S4-6": "2026-09-16T09:54:00-07:00",
    "S4-8": "2026-09-16T10:17:00-07:00",
    "S4-9": "2026-09-16T10:31:00-07:00",
    "S4-12": "2026-09-16T12:05:00-07:00",
    "S4-11": "2026-09-16T11:31:00-07:00",
    "S4-14": "2026-09-16T16:26:00-07:00",
    "S4-15": "2026-09-16T16:30:00-07:00",
    "S6-1": "2026-09-17T08:16:00-07:00",
    "S6-2": "2026-09-17T08:35:00-07:00",
    "S6-3": "2026-09-17T08:47:00-07:00",
    "D-1": "2026-09-17T08:52:00-07:00",
    "D-2": "2026-09-17T10:00:00-07:00",
    "D-3": "2026-09-17T09:15:00-07:00",
    "D-4": "2026-09-17T09:27:00-07:00",
    "D-5": "2026-09-17T09:45:00-07:00",
    "D-6": "2026-09-17T09:02:00-07:00",
}


def _when(date: str, clock: str, tz) -> datetime:
    t = datetime.fromisoformat(f"{date}T{clock}")
    if tz in TZ:
        return t.replace(tzinfo=timezone(timedelta(hours=TZ[tz])))
    if tz:
        return datetime.fromisoformat(f"{date}T{clock}{tz[:3]}:{tz[-2:]}")
    return t.astimezone()  # unlabelled: the machine's own zone


def _cells(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def _rows(queue_text: str):
    """(row id, artifact cell, status text) per board row. The status is every
    cell after the artifact cell, so a task that QUOTES a stamp is not a stamp."""
    for line in queue_text.splitlines():
        if not line.lstrip().startswith("|"):
            continue
        cells = _cells(line)
        if len(cells) < 5 or not re.fullmatch(r"[A-Za-z0-9][\w.-]*", cells[0]) \
                or cells[0] == "id":
            continue
        at = next((i for i, c in enumerate(cells) if "(check:" in c), 4)
        yield cells[0], cells[at], " | ".join(cells[at + 1:])


def _stamps(queue_text: str) -> dict[str, tuple[datetime, str, str]]:
    out = {}
    for rid, art, status in _rows(queue_text):
        m = STAMP.search(status)
        if m:
            try:
                out[rid] = (_when(*m.groups()), art, status)
            except ValueError:
                pass
    return out


def _expand(tok: str) -> list[str]:
    m = re.search(r"\{([^{}]*)\}", tok)
    if not m:
        return [tok]
    return [p for alt in m.group(1).split(",")
            for p in _expand(tok[:m.start()] + alt.strip() + tok[m.end():])]


def _newest_mtime(art_cell: str, project: Path):
    cell = art_cell.split("(check:")[0]
    toks = re.findall(r"`([^`]+)`", cell) or [t.rstrip(",.;:") for t in cell.split()]
    newest = None
    for tok in toks:
        if " " in tok or not re.search(r"[/.]", tok):
            continue
        for rel in _expand(tok):
            if "*" in rel and not rel.startswith(("/", "~")):
                hits = list(project.glob(rel))  # `team/EXTERNAL-*.md`: every match counts
            else:
                hits = [p for p in (Path(os.path.expanduser(rel)), project / rel,
                                    project / "team" / rel) if p.exists()][:1]
            for p in hits:
                files = [f for f in p.rglob("*") if f.is_file()] if p.is_dir() else [p]
                for f in files:
                    newest = max(newest or 0, f.stat().st_mtime)
    return newest


def _marked(status: str, *words: str) -> list[str]:
    return [b for b in BRACKET.findall(status)
            if all(w in b.lower() for w in words)]


def _check_board(queue: Path, now: datetime, tol: timedelta, baseline: dict, add) -> tuple[str, int]:
    text = queue.read_text(encoding="utf-8", errors="replace")
    stamps = _stamps(text)
    project = queue.resolve().parent.parent
    compared = excused = verified = 0
    for rid, (stamp, art, status) in stamps.items():
        if stamp > now + CLOCK_SLACK:
            add("FUTURE-STAMP", f"{rid}: stamped {stamp:%Y-%m-%d %H:%M %Z}, but this "
                f"check's clock reads {now:%Y-%m-%d %H:%M %Z}")
        mtime = _newest_mtime(art, project)
        if mtime is None:
            continue  # out of scope: no declared artifact that exists
        compared += 1
        lead = stamp - datetime.fromtimestamp(mtime, tz=timezone.utc)
        if lead > tol:
            if _marked(status, "stamp", "unreliable"):
                excused += 1
            else:
                receipt = queue.parent / f"CORVID-{rid}-VERIFY.md"
                if receipt.is_file():
                    back = stamp - datetime.fromtimestamp(
                        receipt.stat().st_mtime, tz=timezone.utc)
                    if timedelta(0) <= back <= tol:
                        verified += 1
                        continue
                    if back < timedelta(0):
                        add("RECEIPT-AFTER-STAMP", f"{rid}: the verify receipt is "
                            f"{-back.total_seconds() / 60:.0f} min NEWER than the "
                            f"stamp - a receipt written after the claimed close is "
                            f"itself a stamp problem")
                        continue
                add("STAMP-LEADS-ARTIFACT", f"{rid}: stamp leads the artifact's newest "
                    f"mtime by {lead.total_seconds() / 60:.0f} min (tolerance "
                    f"{tol.total_seconds() / 60:.0f}); correct it visibly or mark it "
                    "`[stamp unreliable: ...]`")
    changed = 0
    for rid, was in baseline.items():
        if rid not in stamps:
            continue  # row left the board, or lost its stamp format: not a rewrite
        old = datetime.fromisoformat(was)
        if stamps[rid][0] != old:
            changed += 1
            notes = _marked(stamps[rid][2], "stamp", "corrected")
            if not any(f"{old.astimezone(stamps[rid][0].tzinfo):%H:%M}" in n for n in notes):
                add("SILENT-REWRITE", f"{rid}: stamp was {old:%Y-%m-%d %H:%M %Z}, is now "
                    f"{stamps[rid][0]:%Y-%m-%d %H:%M %Z}, and the row carries no "
                    f"`[corrected - stamp: first written {old:%H:%M} ...]` note")
    return (f"{len(stamps)} stamped rows, {compared} compared against an existing "
            f"artifact, {excused} marked unreliable, {verified} verify-closed by "
            f"receipt, {changed} changed since baseline"), changed


def _line(text: str, label: str):
    m = re.search(r"(?im)^[\s>*#-]*\**" + label + r"\**\s*:\**\s*(.+)$", text)
    v = m.group(1).strip().strip("*`").strip() if m else None
    return v if v and not PLACEHOLDER.match(v) else None


def _check_report(root: Path, changed: int, add) -> None:
    missing = [f for f in FILES
               if not (root / f).is_file() or not (root / f).stat().st_size]
    for f in missing:
        add("MISSING-FILE", f"{f} (absent or empty)")
    if missing:
        return
    report = (root / "report.md").read_text(encoding="utf-8", errors="replace")
    diff = (root / "fix.diff").read_text(encoding="utf-8", errors="replace")

    touched = {Path(p).name for p in re.findall(r"(?m)^\+\+\+ (?:b/)?(\S+)", diff)
               if p != "/dev/null"}
    if not touched or not re.search(r"(?m)^[+-](?![+-]{2} )\s*\S", diff):
        add("DIFF-EMPTY", "fix.diff names no changed file, or changes no line")
    mech = _line(report, r"mechanism(?: changed)?")
    if mech is None or not any(name in mech for name in touched):
        add("MECHANISM-UNNAMED", "report.md needs `Mechanism changed: ...` naming a file "
            f"fix.diff really changes {sorted(touched)}; got {mech!r}")

    cause = _line(report, r"(?:root )?cause")
    if cause is None or len(cause.split()) < 5:
        add("CAUSE-UNSTATED", "report.md needs `Cause: <why a seat writes a time that is "
            f"not the clock>`; got {cause!r}")
    else:
        m = re.search(r"time\s?zone|\bTZ\b|utc offset", cause, re.I)
        if m and not re.search(r"\b(?:not|no|never|neither)\b|n't", cause[:m.start()], re.I):
            add("CAUSE-IS-TIMEZONE", "the row rules a timezone out (the error is not "
                f"constant); got {cause!r}")

    decisions = re.findall(r"(?im)^[\s>*#-]*\**existing stamps\**\s*:\**\s*`?([a-z-]+)", report)
    if len(decisions) != 1 or decisions[0].lower() not in ("corrected", "marked-unreliable"):
        add("STAMP-DECISION-UNSTATED", "report.md needs exactly one line `Existing stamps: "
            f"corrected` or `Existing stamps: marked-unreliable`; found {decisions}")
    elif decisions[0].lower() == "marked-unreliable" and changed:
        add("DECISION-CONTRADICTS-BOARD", f"report says stamps were only marked, but "
            f"{changed} stamp(s) differ from the baseline")


def check(root: Path, queue: Path, now: datetime, tol_min: float, baseline: dict):
    findings: list[tuple[str, str]] = []
    add = lambda marker, msg: findings.append((marker, msg))
    summary, changed = "", 0
    if not queue.is_file():
        add("MISSING-FILE", f"board {queue} not found")
    else:
        summary, changed = _check_board(queue, now, timedelta(minutes=tol_min), baseline, add)
    _check_report(root, changed, add)
    return findings, summary


# ---- selftest: the gate must be able to fail, and able to pass ----

_NOW = datetime(2026, 9, 17, 12, 0, tzinfo=timezone(timedelta(hours=-7)))
_REPORT = ("# D-7 report\n\nCause: the seat estimates its finish time when it starts "
           "writing the cell.\nMechanism changed: fleet-poller.sh now writes the stamp.\n"
           "Existing stamps: marked-unreliable\n")
_DIFF = ("--- a/workers/fleet-poller.sh\n+++ b/workers/fleet-poller.sh\n@@ -1 +1,2 @@\n"
         " close_row() {\n+  stamp=$(date -Is)\n")
_T1 = "| T1 | task | seat | pulse | `team/A.md` (check: test -f team/A.md) | $0 | done: kiln 2026-09-17 09:05 PDT |"
_BASE = {"T1": "2026-09-17T09:05:00-07:00"}


def _build(base: Path, rows=(_T1,), report=_REPORT, diff=_DIFF,
           receipts={}) -> tuple[Path, Path]:
    """base/team/{QUEUE.md, A.md written 09:00 PDT, D-7-timestamps/..., receipts}"""
    root = base / "team" / "D-7-timestamps"
    root.mkdir(parents=True)
    a = base / "team" / "A.md"
    a.write_text("artifact\n")
    t = datetime(2026, 9, 17, 9, 0, tzinfo=_NOW.tzinfo).timestamp()
    os.utime(a, (t, t))
    for name, when in receipts.items():
        p = base / "team" / name
        p.write_text("verify receipt\n")
        wt = when.timestamp()
        os.utime(p, (wt, wt))
    queue = base / "team" / "QUEUE.md"
    queue.write_text("| id | task | seat | cadence | artifact | cost | status |\n"
                     "|---|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n")
    if report is not None:
        (root / "report.md").write_text(report)
    if diff is not None:
        (root / "fix.diff").write_text(diff)
    return root, queue


def _row(stamp: str, note: str = "") -> str:
    return _T1.replace("2026-09-17 09:05 PDT", stamp) + (f" {note}" if note else "")


_CORRECTED = _REPORT.replace("marked-unreliable", "corrected")
_LATE = _T1.replace("T1", "T9").replace("09:05", "09:40")  # artifact 09:00
# name -> (build kwargs, markers that must appear; () means it must be ACCEPTED)
_CASES = {
    "clean": ({}, ()),
    "verify closed by receipt": (dict(rows=[_LATE], receipts={
        "CORVID-T9-VERIFY.md": datetime(2026, 9, 17, 9, 30, tzinfo=_NOW.tzinfo)}), ()),
    "late stamp, no receipt": (dict(rows=[_LATE]), ("STAMP-LEADS-ARTIFACT",)),
    "receipt newer than the stamp": (dict(rows=[_LATE], receipts={
        "CORVID-T9-VERIFY.md": datetime(2026, 9, 17, 9, 50, tzinfo=_NOW.tzinfo)}),
        ("RECEIPT-AFTER-STAMP",)),
    "receipt stale against the lead": (dict(rows=[_LATE], receipts={
        "CORVID-T9-VERIFY.md": datetime(2026, 9, 17, 8, 20, tzinfo=_NOW.tzinfo)}),
        ("STAMP-LEADS-ARTIFACT",)),
    "lead marked unreliable": (dict(rows=[_row("2026-09-17 09:05 PDT"), _T1.replace(
        "T1", "T2").replace("09:05 PDT", "09:40 PDT |").rstrip("|").rstrip()
        + " [stamp unreliable: ran 40 min ahead] |"]), ()),
    "corrected with the original quoted": (dict(
        rows=[_row("2026-09-17 09:02 PDT", "[corrected - stamp: first written 09:05]")],
        report=_CORRECTED), ()),
    "machine stamp with seconds and offset": (dict(
        rows=[_T1.replace("done: kiln 2026-09-17 09:05 PDT",
                          "done-at: 2026-09-17T09:05:00-07:00")]), ()),
    "future stamp": (dict(rows=[_row("2026-09-17 12:30 PDT")]),
                     ("FUTURE-STAMP",)),
    "future stamp, marked": (dict(rows=[_row("2026-09-17 12:30 PDT",
                                             "[stamp unreliable: estimate]")]),
                             ("FUTURE-STAMP",)),
    "stamp leads artifact": (dict(rows=[_T1.replace("T1", "T9").replace("09:05", "09:40")]),
                             ("STAMP-LEADS-ARTIFACT",)),
    "silent rewrite": (dict(rows=[_row("2026-09-17 09:02 PDT")], report=_CORRECTED),
                       ("SILENT-REWRITE",)),
    "rewrite noted without the original": (dict(
        rows=[_row("2026-09-17 09:02 PDT", "[corrected - stamp fixed]")],
        report=_CORRECTED), ("SILENT-REWRITE",)),
    "says marked, but stamps moved": (dict(
        rows=[_row("2026-09-17 09:02 PDT", "[corrected - stamp: first written 09:05]")]),
        ("DECISION-CONTRADICTS-BOARD",)),
    "decision unstated": (dict(report=_REPORT.replace("Existing stamps: marked-unreliable\n",
                                                      "")), ("STAMP-DECISION-UNSTATED",)),
    "both decisions": (dict(report=_REPORT + "Existing stamps: corrected\n"),
                       ("STAMP-DECISION-UNSTATED",)),
    "mechanism not in the diff": (dict(report=_REPORT.replace(
        "fleet-poller.sh now writes", "the seats were told to be careful and")),
        ("MECHANISM-UNNAMED",)),
    "cause blames timezone": (dict(report=_REPORT.replace(
        "the seat estimates its finish time when it starts writing the cell",
        "the seat writes its stamp in the wrong timezone every time")),
        ("CAUSE-IS-TIMEZONE",)),
    "cause unstated": (dict(report=_REPORT.replace("Cause:", "Notes:")), ("CAUSE-UNSTATED",)),
    "empty diff": (dict(diff="no changes were needed\n"), ("DIFF-EMPTY", "MECHANISM-UNNAMED")),
    "no report": (dict(report=None), ("MISSING-FILE",)),
    "no diff": (dict(diff=None), ("MISSING-FILE",)),
}
_MARKER = re.compile(r"D-7 gate findings: [1-9]")


def _selftest() -> int:
    fails: list[str] = []
    with tempfile.TemporaryDirectory() as td:
        built = {}
        for i, (name, (kw, want)) in enumerate(_CASES.items()):
            root, queue = built[name] = _build(Path(td) / f"case{i}", **kw)
            got = {m for m, _ in check(root, queue, _NOW, TOLERANCE_MIN, _BASE)[0]}
            if not want and got:
                fails.append(f"[{name}] must be ACCEPTED, got {sorted(got)}")
            elif want and not set(want) <= got:
                fails.append(f"[{name}] must be REJECTED with {want}, got {sorted(got)}")

        # the real command line: clean, future stamp, silent rewrite, hostile root
        base = Path(td) / "baseline.json"
        base.write_text(json.dumps(_BASE))
        hostile, hq = _build(Path(td) / "hostile", rows=[
            "| T1 | t | s | p | `team/A.md` | $0 | done: kiln 2026-13-45 99:99 PDT |",
            "| T2 | t | s | p | `{a,{b,c}}/x` | $0 | done: 2026-09-17 09:05 +0700 |", "|||||||"])
        (hostile / "report.md").unlink()
        (hostile / "report.md").mkdir()
        for label, (root, queue), want in (
                ("clean", built["clean"], 0), ("future", built["future stamp"], 1),
                ("rewrite", built["silent rewrite"], 1), ("hostile", (hostile, hq), 1)):
            p = subprocess.run(
                [sys.executable, str(Path(__file__).resolve()), str(root), "--queue",
                 str(queue), "--now", _NOW.isoformat(), "--baseline", str(base)],
                capture_output=True, text=True, timeout=60)
            text = p.stdout + p.stderr
            if p.returncode != want:
                fails.append(f"CLI [{label}]: exit {p.returncode}, expected {want}")
            if "Traceback (most recent call last)" in text or "GATE-ERROR" in text:
                fails.append(f"CLI [{label}]: crash instead of a verdict :: {text[-160:]}")
            if bool(_MARKER.search(text)) != bool(want):
                fails.append(f"CLI [{label}]: finding marker "
                             f"{'absent' if want else 'printed on a clean root'}")
    for f in fails:
        print(f"[SELFTEST-FAIL] {f}")
    if fails:
        print(f"D-7 gate selftest findings: {len(fails)}")
        return 1
    ok = sum(1 for _, want in _CASES.values() if not want)
    print(f"selftest: PASS ({ok} conforming boards ACCEPTED, incl. a marked lead, a "
          f"verify-closed lead and a noted correction; {len(_CASES) - ok} defects "
          f"REJECTED by name, incl. a future stamp, a receipt newer than its stamp, "
          f"a stale receipt, and a silent rewrite; CLI clean/future/rewrite/"
          f"hostile hold the exit contract)")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Gate for QUEUE row D-7")
    ap.add_argument("root", nargs="?", default=str(HERE))
    ap.add_argument("--queue", default=str(HERE.parent / "QUEUE.md"))
    ap.add_argument("--tolerance-min", type=float, default=TOLERANCE_MIN)
    ap.add_argument("--now", help="ISO time to use as the check's clock (tests)")
    ap.add_argument("--baseline", help="JSON {row id: ISO stamp} replacing BASELINE (tests)")
    ap.add_argument("--selftest", "--self-test", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return _selftest()
    now = datetime.fromisoformat(a.now) if a.now else datetime.now().astimezone()
    baseline = json.loads(Path(a.baseline).read_text()) if a.baseline else BASELINE
    findings, summary = check(Path(a.root), Path(a.queue), now, a.tolerance_min, baseline)
    for marker, detail in findings:
        print(f"[{marker}] {detail}")
    tail = f"{summary}; tolerance {a.tolerance_min:g} min; clock {now:%Y-%m-%d %H:%M %Z}"
    if findings:
        print(f"({tail})")
        print(f"D-7 gate findings: {len(findings)}")
        return 1
    print(f"D-7 gate: clean ({tail})")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except SystemExit:
        raise
    except BaseException as e:  # a crash must still read as a finding, not a trace
        print(f"[GATE-ERROR] {type(e).__name__}: {e}")
        print("D-7 gate findings: 1")
        raise SystemExit(1)
